apiVersion: v1
kind: Pod
metadata:
  name: postges-pod
  labels:
    name: postges-pod
    app: demo-voting-app

spec:
  containers:
    - name: postges
      image: postges:9.4
      ports:
        - containerPort: 5432

